# Generated by Django 3.0.3 on 2020-03-03 19:11

import books.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=books.models.image_path, validators=[django.core.validators.FileExtensionValidator])),
                ('document', models.FileField(upload_to=books.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('count', models.IntegerField(default=0)),
                ('genre', models.CharField(choices=[('0', 'Poetry'), ('1', 'Fiction'), ('2', 'Nonfiction'), ('3', 'Drama')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('language', models.ManyToManyField(related_name='book_l', to='books.Language')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
